### ISSUE TITLE
Do you support a function to run simulation paralelly in cluster or using multiple cpus?

### ISSUE THREAD

**Issue by dangliu** [bodkan/slendr#95] opened 2022-06-20 15:01 UTC
Hi Martin,

As title, could you implement this function in future version of slendr?

Thanks,
Dang

**Comment by bodkan** [comment] 2022-06-21 10:49
Hi Dang,

Thanks for the suggestion. The idea makes perfect sense and is -- I'd say -- closely related to what we've discussed in #88. In fact, looking over that issue again, parallel execution was brought up even there. In any case, thank you for helping me prioritize this feature.

Therefore I will follow up in #88 and track my progress there, whenever I get to it, and I will close this as a duplicate.

**Comment by bodkan** [comment] 2022-06-21 10:49
Duplicate of #88

**Closed as completed by bodkan** 2022-06-21 10:49 UTC
